In [2]:
import pandas as pd

In [5]:
a1 = pd.read_csv(r"C:\Users\Varni\Downloads\aggregate\agg_match_stats_0.csv")

In [6]:
d1 = pd.read_csv(r"C:\Users\Varni\Desktop\Course info\Visual\PUBG\deaths.csv")

In [8]:
match_samples=pd.read_csv(r"C:\Users\Varni\Desktop\Course info\Visual\PUBG\sample_matches.csv")

In [5]:
a1.head(5)

,date,game_size,match_id,match_mode,party_size,player_assists,player_dbno,player_dist_ride,player_dist_walk,player_dmg,player_kills,player_name,player_survive_time,team_id,team_placement
0,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,1,2870.72400,1784.847780,117,1,SnuffIes,1106.320,4,18
1,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,1,2938.40723,1756.079710,127,1,Ozon3r,1106.315,4,18
2,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,0.00000,224.157562,67,0,bovize,235.558,5,33
3,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,0.00000,92.935150,0,0,sbahn87,197.553,5,33
4,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,2619.07739,2510.447000,175,2,GeminiZZZ,1537.495,14,11

In [6]:
d1.head(5)

,killed_by,killer_name,killer_placement,killer_position_x,killer_position_y,map,match_id,time,victim_name,victim_placement,victim_position_x,victim_position_y
0,Grenade,KrazyPortuguese,5.0,657725.10,146275.2,MIRAMAR,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,823,KrazyPortuguese,5.0,657725.10,146275.2
1,SCAR-L,nide2Bxiaojiejie,31.0,93091.37,722236.4,MIRAMAR,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,194,X3evolution,33.0,92238.68,723375.1
2,S686,Ascholes,43.0,366921.40,421623.9,MIRAMAR,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,103,CtrlZee,46.0,367304.50,421216.1
3,Down and Out,Weirdo7777,9.0,472014.20,313274.8,MIRAMAR,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,1018,BlackDpre,13.0,476645.90,316758.4
4,M416,Solayuki1,9.0,473357.80,318340.5,MIRAMAR,2U4GBNA0YmnLSqvEycnTjo-KT000vfUnhSA2vfVhVPe1QB...,1018,Vjolt,13.0,473588.50,318418.8

In [7]:
a1_k=a1.copy(deep=True)
a1_k = a1_k.rename(columns={'player_name': 'killer_name'})

In [9]:
a1_v=a1.copy(deep=True)
a1_v = a1_v.rename(columns={'player_name': 'victim_name'})

In [10]:
d1_samp = pd.merge(d1, match_samples, how='inner', on=['match_id'], left_on=None, right_on=None,
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False)

In [13]:
d1_samp['match_id'].nunique()

9205

In [24]:
#d1_samp=d1.sample(n=120000, frac=None, replace=False, weights=None, random_state=7223, axis=None)

In [14]:
c1_k = pd.merge(a1_k, d1_samp, how='inner', on=['match_id','killer_name'], left_on=None, right_on=None,
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False)

In [15]:
c1_v = pd.merge(a1_v, d1_samp, how='inner', on=['match_id','victim_name'], left_on=None, right_on=None,
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False)

In [16]:
len(c1_v)

836885

In [27]:
c1_k.head(5)

,date,game_size,match_id,match_mode,party_size,player_assists,player_dbno,player_dist_ride,player_dist_walk,player_dmg,...,killed_by,killer_placement,killer_position_x,killer_position_y,map,time,victim_name,victim_placement,victim_position_x,victim_position_y
0,2017-11-02T23:14:38+0000,46,2U4GBNA0Ymk--3atnvB2Cy2-kmfWLqeLwaiFMfmzWQFhCk...,tpp,2,0,4,1403.11621,3056.21948,491,...,M16A4,2.0,396685.2,300570.8,ERANGEL,616,RulaSx,28.0,394583.0,288898.8
1,2017-11-02T23:14:38+0000,46,2U4GBNA0Ymk--3atnvB2Cy2-kmfWLqeLwaiFMfmzWQFhCk...,tpp,2,0,2,4244.69775,2571.39038,623,...,Kar98k,1.0,154957.4,415527.1,ERANGEL,1231,CammSlizzleSlays,19.0,156846.8,413291.1
2,2017-11-02T23:14:38+0000,46,2U4GBNA0Ymk--3atnvB2Cy2-kmfWLqeLwaiFMfmzWQFhCk...,tpp,2,1,2,0.00000,3364.34229,479,...,SCAR-L,5.0,247361.6,359915.1,ERANGEL,1615,LoafDumper,9.0,244868.5,362956.6
3,2017-11-02T23:14:38+0000,46,2U4GBNA0Ymk--3atnvB2Cy2-kmfWLqeLwaiFMfmzWQFhCk...,tpp,2,0,2,1923.29053,1308.71973,381,...,AKM,21.0,314883.2,358906.7,ERANGEL,918,Xinatic,3.0,315112.8,359645.0
4,2017-11-02T23:14:38+0000,46,2U4GBNA0Ymk--3atnvB2Cy2-kmfWLqeLwaiFMfmzWQFhCk...,tpp,2,1,1,0.00000,3222.46338,73,...,SCAR-L,5.0,295955.0,440613.4,ERANGEL,1024,Titanruler,15.0,291801.7,444468.7

In [19]:
c1_k.to_csv("killer_stats.csv",encoding='utf-8', index=False)

PermissionError: [Errno 13] Permission denied: 'killer_stats.csv'

In [18]:
c1_v.to_csv("victim_stats.csv",encoding='utf-8', index=False)

In [41]:
player_stats = pd.read_csv("PUBG_Player_Statistics.csv")

In [69]:
player_stats.columns.values

array(['player_name', 'tracker_id', 'solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       'solo_Losses', 'solo_Rating', 'solo_BestRating', 'solo_DamagePg',
       'solo_HeadshotKillsPg', 'solo_HealsPg', 'solo_KillsPg',
       'solo_MoveDistancePg', 'solo_RevivesPg', 'solo_RoadKillsPg',
       'solo_TeamKillsPg', 'solo_TimeSurvivedPg', 'solo_Top10sPg',
       'solo_Kills', 'solo_Assists', 'solo_Suicides', 'solo_TeamKills',
       'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideDistance', 'solo_LongestKill',
       'solo_Heals', 'solo_Revives', 'solo_Boosts', 'solo_DamageDealt',
       'solo_DBNOs', 'duo_KillDeathRatio', 'duo_WinRatio',
       'duo_TimeSurvived', 'duo_RoundsPlayed', 'duo_Wins',
       'duo_WinTop10Ratio', 'duo_Top10s', 'duo_Top10Ratio', 'duo_Losses',
       'duo_Rating', 'duo_BestRating', 'duo_DamagePg',
       'duo_HeadshotKillsPg', 'duo_HealsPg', 'duo_KillsPg',
       'duo_MoveDistancePg', 'duo_RevivesPg', 'duo_RoadKillsPg',
       'duo_TeamKillsPg', 'duo_TimeSurvivedPg', 'duo_Top10sPg',
       'duo_Kills', 'duo_Assists', 'duo_Suicides', 'duo_TeamKills',
       'duo_HeadshotKills', 'duo_HeadshotKillRatio', 'duo_VehicleDestroys',
       'duo_RoadKills', 'duo_DailyKills', 'duo_WeeklyKills',
       'duo_RoundMostKills', 'duo_MaxKillStreaks', 'duo_WeaponAcquired',
       'duo_Days', 'duo_LongestTimeSurvived', 'duo_MostSurvivalTime',
       'duo_AvgSurvivalTime', 'duo_WinPoints', 'duo_WalkDistance',
       'duo_RideDistance', 'duo_MoveDistance', 'duo_AvgWalkDistance',
       'duo_AvgRideDistance', 'duo_LongestKill', 'duo_Heals',
       'duo_Revives', 'duo_Boosts', 'duo_DamageDealt', 'duo_DBNOs',
       'squad_KillDeathRatio', 'squad_WinRatio', 'squad_TimeSurvived',
       'squad_RoundsPlayed', 'squad_Wins', 'squad_WinTop10Ratio',
       'squad_Top10s', 'squad_Top10Ratio', 'squad_Losses', 'squad_Rating',
       'squad_BestRating', 'squad_DamagePg', 'squad_HeadshotKillsPg',
       'squad_HealsPg', 'squad_KillsPg', 'squad_MoveDistancePg',
       'squad_RevivesPg', 'squad_RoadKillsPg', 'squad_TeamKillsPg',
       'squad_TimeSurvivedPg', 'squad_Top10sPg', 'squad_Kills',
       'squad_Assists', 'squad_Suicides', 'squad_TeamKills',
       'squad_HeadshotKills', 'squad_HeadshotKillRatio',
       'squad_VehicleDestroys', 'squad_RoadKills', 'squad_DailyKills',
       'squad_WeeklyKills', 'squad_RoundMostKills', 'squad_MaxKillStreaks',
       'squad_WeaponAcquired', 'squad_Days', 'squad_LongestTimeSurvived',
       'squad_MostSurvivalTime', 'squad_AvgSurvivalTime',
       'squad_WinPoints', 'squad_WalkDistance', 'squad_RideDistance',
       'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt', 'squad_DBNOs'], dtype=object)

In [65]:
solo=player_stats.copy(deep=True)

In [66]:
duo=player_stats.copy(deep=True)

In [67]:
squad=player_stats.copy(deep=True)

In [77]:
solo.head(5)

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,solo_RideDistance,solo_MoveDistance,solo_AvgWalkDistance,solo_AvgRideDistance,solo_LongestKill,solo_Heals,solo_Revives,solo_Boosts,solo_DamageDealt,solo_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,27537.53,56461.84,2202.40,2764.50,304.87,33,0,29,4341.06,0
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,117837.74,165706.51,2017.38,5188.69,351.95,60,0,88,12970.39,0
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,7683.20,14023.99,1375.70,3052.50,125.76,5,0,3,1648.82,0
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,30314.83,47894.53,2197.46,3789.35,412.25,8,0,24,6015.57,0
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,22425.36,39161.77,2789.40,3737.56,307.97,12,0,21,3824.89,0

In [76]:
solo=solo.drop(['duo_KillDeathRatio', 'duo_WinRatio',
       'duo_TimeSurvived', 'duo_RoundsPlayed', 'duo_Wins',
       'duo_WinTop10Ratio', 'duo_Top10s', 'duo_Top10Ratio', 'duo_Losses',
       'duo_Rating', 'duo_BestRating', 'duo_DamagePg',
       'duo_HeadshotKillsPg', 'duo_HealsPg', 'duo_KillsPg',
       'duo_MoveDistancePg', 'duo_RevivesPg', 'duo_RoadKillsPg',
       'duo_TeamKillsPg', 'duo_TimeSurvivedPg', 'duo_Top10sPg',
       'duo_Kills', 'duo_Assists', 'duo_Suicides', 'duo_TeamKills',
       'duo_HeadshotKills', 'duo_HeadshotKillRatio', 'duo_VehicleDestroys',
       'duo_RoadKills', 'duo_DailyKills', 'duo_WeeklyKills',
       'duo_RoundMostKills', 'duo_MaxKillStreaks', 'duo_WeaponAcquired',
       'duo_Days', 'duo_LongestTimeSurvived', 'duo_MostSurvivalTime',
       'duo_AvgSurvivalTime', 'duo_WinPoints', 'duo_WalkDistance',
       'duo_RideDistance', 'duo_MoveDistance', 'duo_AvgWalkDistance',
       'duo_AvgRideDistance', 'duo_LongestKill', 'duo_Heals',
       'duo_Revives', 'duo_Boosts', 'duo_DamageDealt', 'duo_DBNOs',
       'squad_KillDeathRatio', 'squad_WinRatio', 'squad_TimeSurvived',
       'squad_RoundsPlayed', 'squad_Wins', 'squad_WinTop10Ratio',
       'squad_Top10s', 'squad_Top10Ratio', 'squad_Losses', 'squad_Rating',
       'squad_BestRating', 'squad_DamagePg', 'squad_HeadshotKillsPg',
       'squad_HealsPg', 'squad_KillsPg', 'squad_MoveDistancePg',
       'squad_RevivesPg', 'squad_RoadKillsPg', 'squad_TeamKillsPg',
       'squad_TimeSurvivedPg', 'squad_Top10sPg', 'squad_Kills',
       'squad_Assists', 'squad_Suicides', 'squad_TeamKills',
       'squad_HeadshotKills', 'squad_HeadshotKillRatio',
       'squad_VehicleDestroys', 'squad_RoadKills', 'squad_DailyKills',
       'squad_WeeklyKills', 'squad_RoundMostKills', 'squad_MaxKillStreaks',
       'squad_WeaponAcquired', 'squad_Days', 'squad_LongestTimeSurvived',
       'squad_MostSurvivalTime', 'squad_AvgSurvivalTime',
       'squad_WinPoints', 'squad_WalkDistance', 'squad_RideDistance',
       'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt', 'squad_DBNOs'],axis=1)

In [78]:
l1=list(['solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       'solo_Losses', 'solo_Rating', 'solo_BestRating', 'solo_DamagePg',
       'solo_HeadshotKillsPg', 'solo_HealsPg', 'solo_KillsPg',
       'solo_MoveDistancePg', 'solo_RevivesPg', 'solo_RoadKillsPg',
       'solo_TeamKillsPg', 'solo_TimeSurvivedPg', 'solo_Top10sPg',
       'solo_Kills', 'solo_Assists', 'solo_Suicides', 'solo_TeamKills',
       'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideDistance', 'solo_LongestKill',
       'solo_Heals', 'solo_Revives', 'solo_Boosts', 'solo_DamageDealt',
       'solo_DBNOs'])

In [81]:
solo.columns = solo.columns.str.replace('solo_','')

In [83]:
solo['team_type']='solo'

In [84]:
solo.head(10)

,player_name,tracker_id,KillDeathRatio,WinRatio,TimeSurvived,RoundsPlayed,Wins,WinTop10Ratio,Top10s,Top10Ratio,...,MoveDistance,AvgWalkDistance,AvgRideDistance,LongestKill,Heals,Revives,Boosts,DamageDealt,DBNOs,team_type
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,56461.84,2202.40,2764.50,304.87,33,0,29,4341.06,0,solo
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,165706.51,2017.38,5188.69,351.95,60,0,88,12970.39,0,solo
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,14023.99,1375.70,3052.50,125.76,5,0,3,1648.82,0,solo
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,47894.53,2197.46,3789.35,412.25,8,0,24,6015.57,0,solo
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,39161.77,2789.40,3737.56,307.97,12,0,21,3824.89,0,solo
5,coldoxygen,33313,5.73,31.25,22003.22,16,5,0.50,10,62.5,...,91395.30,1940.20,3772.01,298.03,22,0,50,6591.15,0,solo
6,Giken,15585,2.45,8.45,148051.25,142,12,0.18,34,23.9,...,670638.33,1939.00,5189.78,464.37,275,0,371,40409.57,0,solo
7,KoreaNo1,9454,2.71,26.32,26091.14,19,5,0.50,10,52.6,...,95534.14,1270.11,3758.00,260.01,29,0,55,4529.69,0,solo
8,undor,24029,3.68,13.64,49282.41,44,6,0.23,13,29.5,...,165490.88,830.48,1176.55,283.13,67,0,97,14935.28,0,solo
9,Fordune,11289,4.17,25.00,10280.77,8,2,0.25,4,50.0,...,31283.25,3609.51,546.01,183.70,9,0,24,2979.04,0,solo

In [60]:
b=list(a)

In [ ]:
def remove_cat(s):
    return s[5:]

a=[remove_cat(s) for s in b]
a

In [53]:
performances_features=list(['KillDeathRatio','WinRatio','TimeSurvived','RoundsPlayed','Wins','WinTop10Ratio','Top10s','Top10Ratio','Losses','WinPoints'])
ratings_features=list(['Rating','BestRating'])
support_features=list(['Heals','Revives','Boosts','DamageDealt','DBNOs'])
survival_features=list(['Days','LongestTimeSurvived','MostSurvivalTime','AvgSurvivalTime'])
distance_features=list(['WalkDistance','RideDistance','MoveDistance','AvgWalkDistance','AvgRideDistance','LongestKill'])
combat_features=list(['Kills','Assists','Suicides','TeamKills','HeadshotKills','HeadshotKillRatio','VehicleDestroys','RoadKills','DailyKills','WeeklyKills','RoundMostKills','MaxKillStreaks','WeaponAcquired'])

In [54]:
len(performances_features)

10

In [55]:
len(ratings_features)

2

In [85]:
duo=duo.drop(['solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       'solo_Losses', 'solo_Rating', 'solo_BestRating', 'solo_DamagePg',
       'solo_HeadshotKillsPg', 'solo_HealsPg', 'solo_KillsPg',
       'solo_MoveDistancePg', 'solo_RevivesPg', 'solo_RoadKillsPg',
       'solo_TeamKillsPg', 'solo_TimeSurvivedPg', 'solo_Top10sPg',
       'solo_Kills', 'solo_Assists', 'solo_Suicides', 'solo_TeamKills',
       'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideDistance', 'solo_LongestKill',
       'solo_Heals', 'solo_Revives', 'solo_Boosts', 'solo_DamageDealt',
       'solo_DBNOs',
       'squad_KillDeathRatio', 'squad_WinRatio', 'squad_TimeSurvived',
       'squad_RoundsPlayed', 'squad_Wins', 'squad_WinTop10Ratio',
       'squad_Top10s', 'squad_Top10Ratio', 'squad_Losses', 'squad_Rating',
       'squad_BestRating', 'squad_DamagePg', 'squad_HeadshotKillsPg',
       'squad_HealsPg', 'squad_KillsPg', 'squad_MoveDistancePg',
       'squad_RevivesPg', 'squad_RoadKillsPg', 'squad_TeamKillsPg',
       'squad_TimeSurvivedPg', 'squad_Top10sPg', 'squad_Kills',
       'squad_Assists', 'squad_Suicides', 'squad_TeamKills',
       'squad_HeadshotKills', 'squad_HeadshotKillRatio',
       'squad_VehicleDestroys', 'squad_RoadKills', 'squad_DailyKills',
       'squad_WeeklyKills', 'squad_RoundMostKills', 'squad_MaxKillStreaks',
       'squad_WeaponAcquired', 'squad_Days', 'squad_LongestTimeSurvived',
       'squad_MostSurvivalTime', 'squad_AvgSurvivalTime',
       'squad_WinPoints', 'squad_WalkDistance', 'squad_RideDistance',
       'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt', 'squad_DBNOs'],axis=1)

In [86]:
duo.columns = duo.columns.str.replace('duo_','')
duo['team_type']='duo'
duo.head(5)

,player_name,tracker_id,KillDeathRatio,WinRatio,TimeSurvived,RoundsPlayed,Wins,WinTop10Ratio,Top10s,Top10Ratio,...,MoveDistance,AvgWalkDistance,AvgRideDistance,LongestKill,Heals,Revives,Boosts,DamageDealt,DBNOs,team_type
0,BreakNeck,4405,6.50,33.33,21913.81,15,5,0.25,10,66.7,...,95809.08,1252.45,4744.35,401.45,35,2,43,8544.07,40,duo
1,Blackwalk,8199,4.56,35.71,17765.43,14,5,0.36,7,50.0,...,96162.39,1483.98,4109.21,182.84,27,2,43,4744.32,23,duo
2,mercedes_benz,4454,6.55,35.29,23449.22,17,6,0.30,10,58.8,...,99274.93,3185.21,4049.19,354.19,28,2,42,8972.61,36,duo
3,DORA,7729,8.00,66.67,4196.37,3,2,1.00,2,66.7,...,18618.21,3432.07,2774.00,192.89,1,1,6,1302.40,5,duo
4,n2tstar,0,5.03,25.71,142571.50,105,27,0.45,60,57.1,...,594555.10,1827.45,3834.98,362.70,199,26,235,45005.56,216,duo

In [87]:
squad=squad.drop(['solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       'solo_Losses', 'solo_Rating', 'solo_BestRating', 'solo_DamagePg',
       'solo_HeadshotKillsPg', 'solo_HealsPg', 'solo_KillsPg',
       'solo_MoveDistancePg', 'solo_RevivesPg', 'solo_RoadKillsPg',
       'solo_TeamKillsPg', 'solo_TimeSurvivedPg', 'solo_Top10sPg',
       'solo_Kills', 'solo_Assists', 'solo_Suicides', 'solo_TeamKills',
       'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideDistance', 'solo_LongestKill',
       'solo_Heals', 'solo_Revives', 'solo_Boosts', 'solo_DamageDealt',
       'solo_DBNOs','duo_KillDeathRatio', 'duo_WinRatio',
       'duo_TimeSurvived', 'duo_RoundsPlayed', 'duo_Wins',
       'duo_WinTop10Ratio', 'duo_Top10s', 'duo_Top10Ratio', 'duo_Losses',
       'duo_Rating', 'duo_BestRating', 'duo_DamagePg',
       'duo_HeadshotKillsPg', 'duo_HealsPg', 'duo_KillsPg',
       'duo_MoveDistancePg', 'duo_RevivesPg', 'duo_RoadKillsPg',
       'duo_TeamKillsPg', 'duo_TimeSurvivedPg', 'duo_Top10sPg',
       'duo_Kills', 'duo_Assists', 'duo_Suicides', 'duo_TeamKills',
       'duo_HeadshotKills', 'duo_HeadshotKillRatio', 'duo_VehicleDestroys',
       'duo_RoadKills', 'duo_DailyKills', 'duo_WeeklyKills',
       'duo_RoundMostKills', 'duo_MaxKillStreaks', 'duo_WeaponAcquired',
       'duo_Days', 'duo_LongestTimeSurvived', 'duo_MostSurvivalTime',
       'duo_AvgSurvivalTime', 'duo_WinPoints', 'duo_WalkDistance',
       'duo_RideDistance', 'duo_MoveDistance', 'duo_AvgWalkDistance',
       'duo_AvgRideDistance', 'duo_LongestKill', 'duo_Heals',
       'duo_Revives', 'duo_Boosts', 'duo_DamageDealt', 'duo_DBNOs'],axis=1)

In [88]:
squad.columns = squad.columns.str.replace('squad_','')
squad['team_type']='squad'
squad.head(5)

,player_name,tracker_id,KillDeathRatio,WinRatio,TimeSurvived,RoundsPlayed,Wins,WinTop10Ratio,Top10s,Top10Ratio,...,MoveDistance,AvgWalkDistance,AvgRideDistance,LongestKill,Heals,Revives,Boosts,DamageDealt,DBNOs,team_type
0,BreakNeck,4405,5.45,47.51,1064406.38,642,305,0.29,583,90.8,...,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448,squad
1,Blackwalk,8199,5.73,46.81,1176986.52,722,338,0.58,640,88.6,...,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724,squad
2,mercedes_benz,4454,6.08,47.34,1166679.99,733,347,0.47,654,89.2,...,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897,squad
3,DORA,7729,4.77,42.16,777611.90,491,207,0.49,426,86.8,...,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057,squad
4,n2tstar,0,5.70,46.39,669326.90,416,193,0.53,363,87.3,...,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077,squad

In [89]:
split_stats = solo.append([duo, squad])

In [90]:
len(split_stats)

263694

In [91]:
len(player_stats)

87898

In [92]:
split_stats.to_csv("reshaped_stats.csv",encoding='utf-8', index=False)

In [93]:
split_stats.head(5)

,player_name,tracker_id,KillDeathRatio,WinRatio,TimeSurvived,RoundsPlayed,Wins,WinTop10Ratio,Top10s,Top10Ratio,...,MoveDistance,AvgWalkDistance,AvgRideDistance,LongestKill,Heals,Revives,Boosts,DamageDealt,DBNOs,team_type
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,56461.84,2202.40,2764.50,304.87,33,0,29,4341.06,0,solo
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,165706.51,2017.38,5188.69,351.95,60,0,88,12970.39,0,solo
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,14023.99,1375.70,3052.50,125.76,5,0,3,1648.82,0,solo
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,47894.53,2197.46,3789.35,412.25,8,0,24,6015.57,0,solo
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,39161.77,2789.40,3737.56,307.97,12,0,21,3824.89,0,solo